### ISSUE TITLE
App Get Crash in Updated React native version after innstalling SDK

### ISSUE THREAD

**Issue by AnujKumar0204** [cashfree/react-native-cashfree-pg-sdk#24]

**Comment by suhas-cashfree** [comment]
Please add more information

**Comment by AnujKumar0204** [comment]
`FATAL EXCEPTION: pool-32-thread-1
                                                                                                    Process: com.league11, PID: 32046
                                                                                                    android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
                                                                                                    	at com.cashfree.pg.analytics.database.CFDatabaseService.lambda$checkIfPaymentsPresent$3$com-cashfree-pg-analytics-database-CFDatabaseService(Unknown Source:2)
                                                                                                    	at com.cashfree.pg.analytics.database.CFDatabaseService$$ExternalSyntheticLambda3.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)`

**Comment by AnujKumar0204** [comment]
react-native-cli: 2.0.1
react-native: 0.71.3

**Comment by suhas-cashfree** [comment]
@AnujKumar0204 you might have both the versions of cashfree's react-native sdk. remove the old one from your project and clean build

**Comment by AnujKumar0204** [comment]
Thanks,
I forgot to remove previous version.
